site_name: aspen_client
theme: readthedocs
repo_url: https://github.com/RD-Processa/Everco.Services.Aspen.Client.Docs


pages:
- Introducci√≥n: Quickstart.md
- URL del servicio: Hosting.md
- Conectar con Aspen: ManageApiKey.md
- Asegurar una clave API: SecuringApiKey.md
