site_name: aspen_client
theme: readthedocs
repo_url: https://github.com/RD-Processa/Everco.Services.Aspen.Client.Docs


pages:
- Descripci贸n general: Quickstart.md
- Instalaci贸n: Install.md
- URL del servicio: Hosting.md
- Conectar con Aspen: ManageApiKey.md
- Asegurar una clave API: SecuringApiKey.md
- Capturando excepciones: AspenException.md
- Reemplazar componentes: ServiceLocator.md
- M贸dulos del servicio: ModulesAndFeatures.md
  - M贸dulo de configuraciones: SettingsModule.md